# Header
menu:
  首页: /
  常用: /delete
  MM: /mm
  CentOS7: /CentOS7

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# Links
links:

# Miscellaneous
google_analytics: UA-42663954-1
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
duoshuo_shortname: haowaiwai 

# Baidu share
baidushare: true
