# Header
menu:
  Home: /
  Archives: /archives
  Delete: /delete
  MM: /mm
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# Links
links:
  博客: http://hi.baidu.com/haowaiwai

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:
